### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by mtmorgan** [single-cell-data/SOMA#22]
My understanding is that the current naming convention follows closely AnnData, which is very terse, implies familiarity with the underlying data, and is partly discordant with the Feature-Object-Matrix terminology, e.g., `var` seems to be an abbreviation for `feature_annotation` or similar. It would be better to be explicit in the data scheme, rather than terse.

**Comment by pablo-gar** [comment]
@mtmorgan there has been some progress since you filed this issue. It seems that underlying naming structure hasn't changed and there are no plans of changing it.

You can change the latest specification here https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md

If ok with you I'll close this issue.
